Import Pandas

In [1]:
import pandas as pd

Read the `pokemon.csv` file and set the index to `['Type 1', 'Name']`

In [2]:
pokemons = pd.read_csv("Pokemon.csv", index_col=["Type 1", "Name"])
pokemons

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

Sort the pokemons by `Type 1`

In [4]:
pokemons.sort_values("Type 1")

                   #    Type 2  Total   HP  Attack  Defense  Sp. Atk  Sp. Def  \
Type 1 Name
Bug    Sewaddle  540     Grass    310   45      53       70       40       60
       Pinsir    127       NaN    500   65     125      100       55       70
       Burmy     412       NaN    224   40      29       45       29       45
       Scyther   123    Flying    500   70     110       80       55       80
       Joltik    595  Electric    319   50      47       50       57       50
...              ...       ...    ...  ...     ...      ...      ...      ...
Water  Totodile  158       NaN    314   50      65       64       44       48
       Basculin  550       NaN    460   70      92       65       80       55
       Vaporeon  134       NaN    525  130      65       60      110       95
       Panpour   515       NaN    316   50      53       48       53       48
       Chinchou  170  Electric    330   75      38       38       56       56

                 Speed  Generation  Legendary
Type 1 Name
Bug    Sewaddle     42           5      False
       Pinsir       85           1      False
       Burmy        36           4      False
       Scyther     105           1      False
       Joltik       65           5      False
...                ...         ...        ...
Water  Totodile     43           2      False
       Basculin     98           5      False
       Vaporeon     65           1      False
       Panpour      64           5      False
       Chinchou     67           2      False

[800 rows x 11 columns]

Select all the `Fire` pokemons that start with the letter `C`

In [7]:
fire_pokemons = pokemons.loc["Fire"]
fire_pokemons.loc[fire_pokemons.index.str.startswith('C')]

,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,,,,,,,,,,,
Charmander,4,NaN,309,39,52,43,60,50,65,1,False
Charmeleon,5,NaN,405,58,64,58,80,65,80,1,False
Charizard,6,Flying,534,78,84,78,109,85,100,1,False
CharizardMega Charizard X,6,Dragon,634,78,130,111,130,85,100,1,False
CharizardMega Charizard Y,6,Flying,634,78,104,78,159,115,100,1,False
Cyndaquil,155,NaN,309,39,52,43,60,50,65,2,False
Combusken,256,Fighting,405,60,85,60,85,60,55,3,False
Camerupt,323,Ground,460,70,100,70,105,75,40,3,False
CameruptMega Camerupt,323,Ground,560,70,120,100,145,105,20,3,False
Chimchar,390,NaN,309,44,58,44,58,44,61,4,False

Using `agg()` get the `max`, `min` and the `mean` of all the pokemons for the columns `['Attack', 'Defense']` and round them to 1 decimal place.

In [9]:
pokemons.agg({"Attack" : ["max", "min", "mean"], "Defense" : ["max", "min", "mean"]}).round(1)

      Attack  Defense
max    190.0    230.0
min      5.0      5.0
mean    79.0     73.8

Create a function that checks the Attack of a pokemon. If the `Attack` is over 100, it should now display `'STRONG'`, if it is less than that, it should display `'WEAK'`. Update the DataFrame to display this new Attack column`

In [11]:
def strenght(attack:int)->str:
    if attack > 100:
        return "STRONG"
    else:
        return "WEAK"
    
pokemons["Attack"] = pokemons["Attack"].apply(strenght)
pokemons

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45    WEAK       49
        Ivysaur                  2  Poison    405  60    WEAK       63
        Venusaur                 3  Poison    525  80    WEAK       83
        VenusaurMega Venusaur    3  Poison    625  80    WEAK      123
Fire    Charmander               4     NaN    309  39    WEAK       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50    WEAK      150
        DiancieMega Diancie    719   Fairy    700  50  STRONG      110
Psychic HoopaHoopa Confined    720   Ghost    600  80  STRONG       60
        HoopaHoopa Unbound     720    Dark    680  80  STRONG       60
Fire    Volcanion              721   Water    600  80  STRONG      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]

Create a new column called `Reversed` which holds each pokemon name reversed

In [13]:
pokemons["Reversed"]=pokemons.index.get_level_values("Name").str[::-1]
pokemons

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45    WEAK       49
        Ivysaur                  2  Poison    405  60    WEAK       63
        Venusaur                 3  Poison    525  80    WEAK       83
        VenusaurMega Venusaur    3  Poison    625  80    WEAK      123
Fire    Charmander               4     NaN    309  39    WEAK       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50    WEAK      150
        DiancieMega Diancie    719   Fairy    700  50  STRONG      110
Psychic HoopaHoopa Confined    720   Ghost    600  80  STRONG       60
        HoopaHoopa Unbound     720    Dark    680  80  STRONG       60
Fire    Volcanion              721   Water    600  80  STRONG      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary  \
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

                                            Reversed
Type 1  Name
Grass   Bulbasaur                          ruasabluB
        Ivysaur                              ruasyvI
        Venusaur                            ruasuneV
        VenusaurMega Venusaur  ruasuneV ageMruasuneV
Fire    Charmander                        rednamrahC
...                                              ...
Rock    Diancie                              eicnaiD
        DiancieMega Diancie      eicnaiD ageMeicnaiD
Psychic HoopaHoopa Confined      denifnoC apooHapooH
        HoopaHoopa Unbound        dnuobnU apooHapooH
Fire    Volcanion                          noinacloV

[800 rows x 12 columns]

Reset the index so that only `Name` shows as the index

In [22]:
pokemons.set_index("Name")

,Type 1,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Reversed
Name,,,,,,,,,,,,,
Bulbasaur,Grass,1,Poison,318,45,WEAK,49,65,65,45,1,False,ruasabluB
Ivysaur,Grass,2,Poison,405,60,WEAK,63,80,80,60,1,False,ruasyvI
Venusaur,Grass,3,Poison,525,80,WEAK,83,100,100,80,1,False,ruasuneV
VenusaurMega Venusaur,Grass,3,Poison,625,80,WEAK,123,122,120,80,1,False,ruasuneV ageMruasuneV
Charmander,Fire,4,NaN,309,39,WEAK,43,60,50,65,1,False,rednamrahC
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,719,Fairy,600,50,WEAK,150,100,150,50,6,True,eicnaiD
DiancieMega Diancie,Rock,719,Fairy,700,50,STRONG,110,160,110,110,6,True,eicnaiD ageMeicnaiD
HoopaHoopa Confined,Psychic,720,Ghost,600,80,STRONG,60,150,130,70,6,True,denifnoC apooHapooH
HoopaHoopa Unbound,Psychic,720,Dark,680,80,STRONG,60,170,130,80,6,True,dnuobnU apooHapooH
Volcanion,Fire,721,Water,600,80,STRONG,120,130,90,70,6,True,noinacloV

In [21]:
pokemons = pokemons.reset_index()

In [20]:
pokemons

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45    WEAK       49
        Ivysaur                  2  Poison    405  60    WEAK       63
        Venusaur                 3  Poison    525  80    WEAK       83
        VenusaurMega Venusaur    3  Poison    625  80    WEAK      123
Fire    Charmander               4     NaN    309  39    WEAK       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50    WEAK      150
        DiancieMega Diancie    719   Fairy    700  50  STRONG      110
Psychic HoopaHoopa Confined    720   Ghost    600  80  STRONG       60
        HoopaHoopa Unbound     720    Dark    680  80  STRONG       60
Fire    Volcanion              721   Water    600  80  STRONG      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary  \
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

                                            Reversed
Type 1  Name
Grass   Bulbasaur                          ruasabluB
        Ivysaur                              ruasyvI
        Venusaur                            ruasuneV
        VenusaurMega Venusaur  ruasuneV ageMruasuneV
Fire    Charmander                        rednamrahC
...                                              ...
Rock    Diancie                              eicnaiD
        DiancieMega Diancie      eicnaiD ageMeicnaiD
Psychic HoopaHoopa Confined      denifnoC apooHapooH
        HoopaHoopa Unbound        dnuobnU apooHapooH
Fire    Volcanion                          noinacloV

[800 rows x 12 columns]